"""
.. include:: ../extras/chars.md
"""

import random

__all__ = (
    "INVISIBLE_CHARACTERS",
    "INVISIBLE_CHARACTER",
    "ARROW_LEFT",
    "ARROW_RIGHT",
    "ARROW_UP",
    "ARROW_DOWN",
    "BULLET_POINT",
)

ZERO_WIDTH_CHARACTERS = [
    "\N{ZERO WIDTH NO-BREAK SPACE}",
    "\N{ZERO WIDTH JOINER}",
    "\N{WORD JOINER}",
    "\N{ZERO WIDTH SPACE}",
    "\N{ZERO WIDTH NON-JOINER}",
]
INVISIBLE_CHARACTERS = ZERO_WIDTH_CHARACTERS + ["\N{BRAILLE PATTERN BLANK}"]
INVISIBLE_CHARACTER = random.choice(INVISIBLE_CHARACTERS)

ARROW_LEFT = "\N{LEFTWARDS ARROW}"
ARROW_RIGHT = "\N{RIGHTWARDS ARROW}"
ARROW_UP = "\N{UPWARDS ARROW}"
ARROW_DOWN = "\N{DOWNWARDS ARROW}"

BULLET_POINT = "\N{BULLET}"
